# Playground

In [1]:
import os
import ast
import json
import torch
import torch.nn as nn
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.preprocessing import OneHotEncoder

In [2]:
ROOT = Path('../asun/Smart-Trash/data/isbnet/')
metadata = pd.read_csv(ROOT / 'metadata.csv')

In [3]:
metadata

filepath  category  \
0    ../asun/Smart-Trash/data/isbnet/cans/9A/202001...      cans   
1    ../asun/Smart-Trash/data/isbnet/cans/9A/202001...      cans   
2    ../asun/Smart-Trash/data/isbnet/cans/9A/202001...      cans   
3    ../asun/Smart-Trash/data/isbnet/cans/6B/cans29...      cans   
4    ../asun/Smart-Trash/data/isbnet/cans/6B/IMG_73...      cans   
..                                                 ...       ...   
883  ../asun/Smart-Trash/data/isbnet/tetrapak/8A/tr...  tetrapak   
884  ../asun/Smart-Trash/data/isbnet/tetrapak/8A/tr...  tetrapak   
885  ../asun/Smart-Trash/data/isbnet/tetrapak/8A/20...  tetrapak   
886  ../asun/Smart-Trash/data/isbnet/tetrapak/8A/tr...  tetrapak   
887  ../asun/Smart-Trash/data/isbnet/tetrapak/8A/20...  tetrapak   

                    categorial_time trashcan_id  \
0    (0, 0, 0, 1, 1, 1, 0, 0, 0, 0)          9A   
1    (0, 0, 0, 1, 1, 1, 0, 0, 0, 0)          9A   
2    (0, 0, 0, 1, 1, 1, 0, 0, 0, 0)          9A   
3    (0, 0, 0, 1, 1, 1, 0, 0, 0, 0)          6B   
4    (0, 0, 0, 1, 1, 1, 0, 0, 0, 0)          6B   
..                              ...         ...   
883  (0, 1, 1, 1, 1, 1, 0, 1, 1, 0)          8A   
884  (0, 1, 1, 1, 1, 1, 0, 1, 1, 0)          8A   
885  (0, 1, 1, 1, 1, 1, 0, 1, 1, 0)          8A   
886  (0, 1, 1, 1, 1, 1, 0, 1, 1, 0)          8A   
887  (0, 1, 1, 1, 1, 1, 0, 1, 1, 0)          8A   

                      trashcan_time  \
0    (0, 0, 0, 0, 0, 0, 0, 1, 1, 1)   
1    (0, 0, 0, 0, 0, 0, 0, 1, 1, 1)   
2    (0, 0, 0, 0, 0, 0, 0, 1, 1, 1)   
3    (0, 1, 0, 1, 0, 0, 1, 0, 0, 0)   
4    (0, 1, 0, 1, 0, 0, 1, 0, 0, 0)   
..                              ...   
883  (0, 0, 0, 1, 1, 1, 1, 1, 0, 0)   
884  (0, 0, 0, 1, 1, 1, 1, 1, 0, 0)   
885  (0, 0, 0, 1, 1, 1, 1, 1, 0, 0)   
886  (0, 0, 0, 1, 1, 1, 1, 1, 0, 0)   
887  (0, 0, 0, 1, 1, 1, 1, 1, 0, 0)   

                                     trashcan_location  \
0    [(24.07, 7.791), (2.209, 7.907), (8.372, 6.047...   
1    [(24.07, 7.791), (2.209, 7.907), (8.372, 6.047...   
2    [(24.07, 7.791), (2.209, 7.907), (8.372, 6.047...   
3    [(0.465, 7.442), (15.116, 6.744), (10.349, 7.5...   
4    [(0.465, 7.442), (15.116, 6.744), (10.349, 7.5...   
..                                                 ...   
883  [(17.558, 31.977), (7.558, 1.86), (9.186, 13.8...   
884  [(17.558, 31.977), (7.558, 1.86), (9.186, 13.8...   
885  [(17.558, 31.977), (7.558, 1.86), (9.186, 13.8...   
886  [(17.558, 31.977), (7.558, 1.86), (9.186, 13.8...   
887  [(17.558, 31.977), (7.558, 1.86), (9.186, 13.8...   

                                             landmarks  
0    ['theater', 'printer', 'stairwell', 'bathroom'...  
1    ['theater', 'printer', 'stairwell', 'bathroom'...  
2    ['theater', 'printer', 'stairwell', 'bathroom'...  
3              ['bathroom', 'stairwell', 'couch_area']  
4              ['bathroom', 'stairwell', 'couch_area']  
..                                                 ...  
883  ['cafeteria', 'stairwell', 'bathroom', 'librar...  
884  ['cafeteria', 'stairwell', 'bathroom', 'librar...  
885  ['cafeteria', 'stairwell', 'bathroom', 'librar...  
886  ['cafeteria', 'stairwell', 'bathroom', 'librar...  
887  ['cafeteria', 'stairwell', 'bathroom', 'librar...  

[888 rows x 7 columns]

In [4]:
metalabels = json.load(open(ROOT / 'metalabels.json'))

In [5]:
land_dict = metalabels['landmarks']

In [6]:
def encode(landmarks):
    one_hot = np.zeros(len(land_dict))
    for landmark in landmarks:
        one_hot[land_dict[landmark]] = 1.
    return one_hot

In [7]:
def pythag(coor: list) -> float:
    return np.linalg.norm(coor, ord=2)

In [8]:
encode(ast.literal_eval(metadata.iloc[0, 6]))

array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.])

In [11]:
metadata['categorial_time'] = metadata['categorial_time'].apply(ast.literal_eval)

In [9]:
metadata['trashcan_location'] = metadata['trashcan_location'].apply(ast.literal_eval)

In [10]:
metadata['trashcan_time'] = metadata['trashcan_time'].apply(ast.literal_eval)

In [16]:
metadata['landmarks'] = metadata.landmarks.apply(ast.literal_eval)

In [17]:
metadata.iloc[0,6]

['theater', 'printer', 'stairwell', 'bathroom', 'library']

In [18]:
landmarks = encode(metadata.iloc[0, 6])

In [22]:
trashcan_location = metadata.iloc[0, 5]

In [19]:
landmarks

array([1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0.])

In [24]:
distances = [pythag(v) for v in trashcan_location]

In [26]:
for index, i in enumerate(metadata.iloc[0, 6]):
    landmarks[land_dict[i]] = distances[index]

In [27]:
landmarks

array([25.29949764,  8.2097704 , 10.32746789, 19.21819914, 28.10034827,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ])